# Generated by Django 5.0.3 on 2024-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookAuthor', models.TextField()),
                ('bookName', models.TextField()),
                ('bookDate', models.DateField()),
                ('bookPageCount', models.IntegerField()),
                ('bookInstances', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookANDReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.TextField()),
                ('readerID', models.TextField()),
                ('dateIssue', models.DateField()),
                ('dateIreceipt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerFirstName', models.TextField()),
                ('readerSecondName', models.TextField()),
                ('bookBirthday', models.DateField()),
                ('hashPassword', models.TextField()),
            ],
        ),
    ]
